namespace RefApp.Models;

/// <summary>
/// Exhaustive list of all cities, towns, communes and villages in Arad County (Județul Arad).
/// Used to validate and autocomplete location inputs throughout the app.
/// </summary>
public static class AradLocalities
{
    public static readonly IReadOnlyList<string> All = new[]
    {
        // ── Municipii / Orașe ──────────────────────────────────────────
        "Arad",
        "Chișineu-Criș",
        "Curtici",
        "Ineu",
        "Lipova",
        "Nădlac",
        "Pâncota",
        "Sântana",
        "Sebiș",

        // ── Comune & sate ──────────────────────────────────────────────
        "Apateu",
        "Archișag",
        "Archiș",
        "Avram Iancu",
        "Bârzava",
        "Beliu",
        "Birchiș",
        "Bocsig",
        "Brazii",
        "Bujac",
        "Buteni",
        "Cărand",
        "Cermei",
        "Chesinț",
        "Chisindia",
        "Cil",
        "Conop",
        "Covasânț",
        "Craiva",
        "Dezna",
        "Dieci",
        "Dorobanți",
        "Drauț",
        "Dud",
        "Fântânele",
        "Felnac",
        "Frumuseni",
        "Frumușeni",
        "Galșa",
        "Ghioroc",
        "Grăniceri",
        "Gurahonț",
        "Gurba",
        "Hălmagiu",
        "Hălmăgel",
        "Honțișor",
        "Horia",
        "Ignești",
        "Iratoșu",
        "Iulia",
        "Livada",
        "Lupeșu",
        "Macea",
        "Mailat",
        "Mândruloc",
        "Mișca",
        "Mocrea",
        "Moneasa",
        "Munar",
        "Neudorf",
        "Olari",
        "Olău",
        "Ostrov",
        "Pecica",
        "Peregu Mare",
        "Peregu Mic",
        "Petriș",
        "Pilu",
        "Pleșcuța",
        "Șicula",
        "Sâmbăteni",
        "Sânmartin",
        "Sânpaul",
        "Sânpetru German",
        "Satu Nou",
        "Săvârșin",
        "Secusigiu",
        "Semlac",
        "Sintea Mare",
        "Socodor",
        "Șeitin",
        "Șepreuș",
        "Șimand",
        "Șiria",
        "Șofronea",
        "Șomoșcheș",
        "Tauț",
        "Târnova",
        "Timișești",
        "Ususău",
        "Vărșand",
        "Vârfurile",
        "Vinga",
        "Vladimirescu",
        "Voivodeni",
        "Zădăreni",
        "Zărand",
        "Zerind",
        "Zimandu Nou",
        "Zimandcuz",
        "Țipar",
        "Unirea",
        "Zăbalț",
        "Gurba",
        "Aldești",
        "Avram Iancu",
    }.Distinct().OrderBy(x => x).ToList();
}
